넘파이로 배열 정의 하기 

In [1]:
import numpy as np

In [3]:
a = np.array([[2,3],[5,2]])
a # 2차원 배열 2X2

array([[2, 3],
       [5, 2]])

배열 슬라이싱 하기 

In [4]:
d = np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
d # 3차원 배열 3X5

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [5, 7, 8, 9, 9]])

0부터 시작한다는 것 주의하고 생각하기

In [5]:
d[1][2] # 2행, 3열에 위치한 수 반환

5

In [6]:
d[1,2]  # 2행, 3열에 위치한 수 반환

5

In [7]:
d[1:, 3:] # 1행 다음, 3열 다음 수만 슬라이싱 

array([[6, 7],
       [9, 9]])

배열의 크기 알아내기 shape

In [10]:
d = np.array([[2,3,4,5,6]])
d.shape 

(1, 5)

In [11]:
e = np.array([[1,2,3,4], [3,4,5,6]])
e.shape 

(2, 4)

배열의 원소 유형 확인하기 dtype

In [12]:
d.dtype

dtype('int32')

배열 유형 바꾸기 astype

In [18]:
data = np.arange(1,5) # 1부터 4까지로 이루어진 배열을 생성
print(data.dtype)

data = data.astype('float64')
print(data.dtype)

int32
float64


넘파이 함수 알아보기
- np.zeros() 함수는 0으로 이뤄진 배열을 만들기 

In [19]:
np.zeros((2,10)) # 행이 2이고, 열이 10이며 각 원소가 0인 배열 만들기 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

- np.ones() 함수는 1로 만들어진 배열 만들기 

In [20]:
np.ones((2,10)) # 행이 2이고, 열이 10이며 각 원소가 1인 배열 만들기 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

- np.transpose() 함수는 행과 열을 바꾸기 

In [23]:
a = np.ones((2,3)) # 원소가 전부 1인 2x3 배열 만들기 
print(a)
print()
b = np.transpose(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


배열의 사칙연산 

In [24]:
arr1 = np.array([[2,3,4], [6,7,8]])
arr2 = np.array([[12,23,14], [36,47,58]])

- 덧셈 : 같은 자리의 원소끼리 더함

In [25]:
arr1 + arr2

array([[14, 26, 18],
       [42, 54, 66]])

- 뺄셈 : 같은 자리의 원소끼리 뺌

In [26]:
arr1 - arr2

array([[-10, -20, -10],
       [-30, -40, -50]])

- 곱셈 : 같은 자리의 원소끼리 곱함

In [27]:
arr1 * arr2

array([[ 24,  69,  56],
       [216, 329, 464]])

- 나누기 : 같은 자리의 원소끼리 나누기

In [28]:
arr1 / arr2

array([[0.16666667, 0.13043478, 0.28571429],
       [0.16666667, 0.14893617, 0.13793103]])

브로드캐스팅   
크기가 서로 다른 배열끼리 더하기 

In [29]:
arr3 = np.array([100,200,300])

In [30]:
# 크기가 다름 

print(arr1.shape)
print(arr3.shape)

(2, 3)
(3,)


In [31]:
# arr1[0] 과 arr1[1]에 각각 더해졌음 
arr1 + arr3

array([[102, 203, 304],
       [106, 207, 308]])

브로드캐스팅이 되지 않는 경우 

In [32]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr4.shape)
print()
print(arr1.shape)
print()
print(arr1 + arr4) # 행과 열의 크기가 모두 다 다른 배열은 더 할수 없음 

(10,)

(2, 3)



ValueError: operands could not be broadcast together with shapes (2,3) (10,) 

In [36]:
arr5 = np.array([[9],[3]])
print(arr5.shape)
print()

print(arr1.shape)
print()

print(arr1 + arr5)

(2, 1)

(2, 3)

[[11 12 13]
 [ 9 10 11]]


파이썬 리스트와 배열의 차이점

In [38]:
d = np.array([[1,2,3,4,], [2,3,4,5,6], [3,4,5,6,7]])
d_list = [[1,2,3,4,5],
          [2,3,4,5,6],
          [3,4,5,6,7]]

print(d_list)
print(type(d_list))
print()

d[:2] = 0
print(d)

d_list[:2] = 0 # 에러 발생 
print(d_list)

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7]]
<class 'list'>

[0 0 list([3, 4, 5, 6, 7])]


TypeError: can only assign an iterable

인덱싱과 슬라이싱 

In [39]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr4[:5]

array([0, 1, 2, 3, 4])

In [41]:
arr4[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [44]:
arr1 = np.array([[2,3,4], [6,7,8]])
print(arr1[1,2])
print()
print(arr1[:2])

8

[[2 3 4]
 [6 7 8]]


In [45]:
from scipy import stats